const {test}=require('node:test');const assert=require('node:assert/strict');const app=require('./app-helper.cjs');
function find(t,p){if(!t||typeof t!=='object')return;if(p(t))return t;for(const c of [t.props?.children||[]].flat(9)){const r=find(c,p);if(r)return r;}}
test('beginner daily context offers choices instead of requiring keyboard recall',()=>{const a=app();a.run("var w=buildWord({word:'Exulter',definition:'Manifester une joie intense',example_1:'Les joueurs exultent après leur victoire.',example_cloze_1:'Les joueurs […] après leur victoire.'});");const t=a.render('RoutineContext({word:w,words:[w],level:1,onAnswer:()=>{}})');assert.equal(find(t,n=>n.type==='input'),undefined);assert.ok(find(t,n=>n.type?.name==='StepChoice'||n.type?.name==='LearningCard'));});
test('missing vetted QCM teaches a card rather than imposing letter typing',()=>{const a=app();a.run("var w=buildWord({word:'Exulter',definition:'Manifester une joie intense'});");const t=a.render('SafeRecallFallback({word:w,onAnswer:()=>{}})');assert.equal(t.type.name,'LearningCard');});
test('daily rotation reserves newcomers and due consolidated words even with a large active pool',()=>{const a=app();a.run("var ws=buildWords(SEED_WORDS);var s={progress:{},meta:{}};ws.slice(0,12).forEach(w=>s.progress[w.id]={...EMPTY_PROGRESS,seen:2,learning:{phase:'active',lastSeenDay:'2026-10-04'}});s.progress[ws[12].id]={...EMPTY_PROGRESS,seen:20,next:addDays(-2),repetitions:3,learning:{phase:'consolidated'}};var session=buildDailySession(s,ws);");assert.equal(a.run('session.discover.filter(w=>!readP(s,w.id).seen).length'),2);assert.equal(a.run('session.review.some(w=>w.id===ws[12].id)'),true);assert.ok(a.run('session.review.length')<=10);assert.ok(a.run('buildDailyQueues(session).flat().length')<=30);});
test('neutral ambiguous question does not change errors or schedule',()=>{const a=app();a.run("var s={progress:{a:{...EMPTY_PROGRESS,seen:10,wrong:3,next:addDays(6)}},meta:{}};var before=JSON.stringify(s.progress.a);var after=gradeWord(s,'a','good','recog',0,{neutral:true,kind:'meaning',assisted:true});");assert.equal(a.run('JSON.stringify(after.progress.a)'),a.run('before'));});
test('two distinct days of recognition unlock recall, and neutral attempts do not consolidate',()=>{const a=app();assert.equal(a.run("AtelierLearning.level({seen:8,learning:{phase:'active',meaningDays:{'2026-10-02':1,'2026-10-03':1}}},'2026-10-05')"),3);});
test('reporting an ambiguous QCM excludes it on future visits without changing vocabulary',()=>{const a=app();a.run('var ws=buildWords(SEED_WORDS);var w=ws.find(w=>w.word==="Anaphore");');assert.ok(a.run('smartDistractors(w,ws).length')>=2);a.run('reportAmbiguousQcm(w)');assert.equal(a.run('smartDistractors(w,ws).length'),0);assert.ok(a.run('ws.some(x=>x.id===w.id)'));});
test('past errors stop marking a word fragile after several recent successful encounters',()=>{const a=app();a.run("var s={progress:{a:{...EMPTY_PROGRESS,seen:100,wrong:80,correct:20,next:addDays(5),lastWrongDay:'2026-09-01',recentResults:[true,true,true,true,true]}},meta:{}};");assert.equal(a.run("wordStatus(s,{id:'a'})"),'En cours');});
test('quiz fallback carries assisted and neutral evidence to grading',()=>{const a=app();a.run("var ws=buildWords([{word:'Exulter',definition:'Manifester une joie intense'}]);var s={progress:{[ws[0].id]:{...EMPTY_PROGRESS,seen:10,next:addDays(-1),learning:{phase:'consolidated'}}},meta:{}};");const expr='QuizTabNew({words:ws,state:s,setState:n=>s=n,onMilestone:()=>{}})';find(a.render(expr),t=>t.type?.name==='Btn'&&t.props.variant==='primary').props.onClick();let q=find(a.render(expr),t=>t.type?.name==='SafeRecallFallback');a.run('var oldNext=s.progress[ws[0].id].next;var before=JSON.stringify(s.progress[ws[0].id]);');q.props.onAnswer(true,'recog',{kind:'meaning',assisted:true,neutral:true});assert.equal(a.run('JSON.stringify(s.progress[ws[0].id])'),a.run('before'));assert.equal(a.run('s.meta.xp||0'),0);});
test('words without example metadata can consolidate after genuine multi-day recalls',()=>{const a=app();a.run("var s={progress:{},meta:{}};s=gradeWord(s,'a','good','recog',0,{kind:'meaning',assisted:true});s=gradeWord(s,'a','good','prod',0,{kind:'recall',assisted:false});");a.advance(86400000);a.run("s=gradeWord(s,'a','good','recog',0,{kind:'meaning',assisted:true});s=gradeWord(s,'a','good','prod',0,{kind:'recall',assisted:false});");assert.equal(a.run('s.progress.a.learning.phase'),'consolidated');});
test('neutral review consultation cannot earn a streak, XP or a perfect-session bonus',()=>{const a=app();a.run('var ws=buildWords(SEED_WORDS).slice(0,1);var s={progress:{},meta:{}};');const expr="QuizSession({words:ws,state:s,setState:n=>s=n,onMilestone:()=>{},onBack:()=>{},title:'test',color:C.blue})";a.render(expr);a.slots[1]=true;a.slots[2]=a.run('ws');find(a.render(expr),t=>t.type?.name==='ReviewQuizChoice').props.onAnswer(true,'recog',{neutral:true,kind:'meaning',assisted:true});assert.equal(a.slots[4],0);assert.equal(a.slots[5],0);assert.equal(a.slots[6][0].neutral,true);assert.equal(a.slots[6].every(e=>e.ok&&!e.neutral),false);});
test('a large learning pool rotates across days instead of repeating the same favourites',()=>{const a=app();a.run("var ws=buildWords(Array.from({length:30},(_,i)=>({word:'Terme'+i,definition:'Sens distinct '+i})));var s={progress:{},meta:{}};ws.slice(0,15).forEach(w=>s.progress[w.id]={...EMPTY_PROGRESS,seen:4,wrong:100,next:addDays(10),learning:{phase:'active',lastSeenDay:'2026-10-01'}});var visited=new Set();");for(let day=0;day<4;day++){a.run("var session=buildDailySession(s,ws);session.review.forEach(w=>{visited.add(w.id);s=gradeWord(s,w.id,'good','recog',0,{kind:'meaning',assisted:true});});");a.advance(86400000);}assert.equal(a.run('ws.slice(0,15).every(w=>visited.has(w.id))'),true);});
test('later recall lets the learner choose help before any keyboard challenge',()=>{const a=app();a.run("var w=buildWord({word:'Exulter',definition:'Manifester une joie intense'});var result=null;");const expr='RecallChallenge({word:w,onAnswer:(ok,mode,e)=>result=e})';let t=a.render(expr);assert.equal(find(t,n=>n.type==='input'),undefined);find(t,n=>n.props?.label==='Retrouver avec un indice').props.onClick();t=a.render(expr);const q=find(t,n=>n.type?.name==='GuidedRecall');assert.equal(q.props.level,1);q.props.onAnswer({ok:true,assisted:true,kind:'recall'});assert.equal(a.run('result.assisted'),true);});
test('a distractor is invalidated when its full meaning changes even if its short definition stays',()=>{const a=app();a.run("var ws=buildWords([{word:'Alpha',definition_courte:'Appel à la peur',definition:'Argument fondé sur la peur',qcm_definition:'Appel à la peur',qcm_distractors:[{word:'Beta',definition:'Enveloppe vivante de la Terre',full_definition:'Ancien sens complet B'}]},{word:'Beta',definition_courte:'Enveloppe vivante de la Terre',definition:'Nouveau sens complet B'}]);");assert.equal(a.run('smartDistractors(ws[0],ws).length'),0);});
